
name: ci

on:
  push:
    tags:
    - 'v*.*.*'

env:
  GOLANGCI_LINT_VERSION: '1.32.2'
  MAGE_VERSION: '1.10.0'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install Mage
      uses: nickhstr/action-setup-mage@v1.0.0
      with:
        version: ${{ env.MAGE_VERSION }}

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v${{ env.GOLANGCI_LINT_VERSION }}


    - name: Build and test
      run: |
        mage -v buildAll
        export CGO_ENABLED=0
        mage -v lint
        mage -v coverage

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          TODO: change me
        draft: true
        prerelease: false

    - name: Upload plugin to release
      id: upload-release-asset-linux
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/mac_linux_amd64
        asset_name: mac_linux_amd64
        asset_content_type: application/zip
    - name: Upload plugin to release
      id: upload-release-asset-darwin
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/mac_darwin_amd64
        asset_name: mac_darwin_amd64
        asset_content_type: application/zip
    - name: Upload plugin to release
      id: upload-release-asset-windows
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/mac_windows_amd64
        asset_name: mac_windows_amd64
        asset_content_type: application/zip
